"""Read-only probe for Codex app-server state evidence.

This module intentionally separates raw Codex protocol axes from product-facing
traffic-light states. It does not install hooks, start the UI, or treat simulated
events as real VSCode extension state.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import tempfile
import time
from collections.abc import Iterable, Mapping
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from codex_traffic_lights.state_mapper import CodexStateMapper

THREAD_STATUS_RE = re.compile(r'\{\s*"type"\s*:\s*"(?P<value>[^"]+)"')
STRING_UNION_RE_TEMPLATE = r"export\s+type\s+{name}\s*=\s*(?P<body>[^;]+);"
STRING_LITERAL_RE = re.compile(r'"(?P<value>[^"]+)"')

NON_IDLE_SIMULATION_EVENTS: tuple[dict[str, object], ...] = (
    {
        "candidate_product_status": "OFFLINE",
        "source": "product-fallback",
        "event": {"transport": "unavailable", "codex_process": "missing"},
        "mapped_by_current_code": None,
    },
    {
        "candidate_product_status": "NOT_LOADED",
        "source": "ThreadStatus",
        "event": {"status": {"type": "notLoaded"}},
        "mapped_by_current_code": None,
    },
    {
        "candidate_product_status": "WORKING",
        "source": "ThreadStatus",
        "event": {"status": {"type": "active", "activeFlags": []}},
    },
    {
        "candidate_product_status": "WAITING_APPROVAL",
        "source": "ThreadStatus.activeFlags",
        "event": {"status": {"type": "active", "activeFlags": ["waitingOnApproval"]}},
    },
    {
        "candidate_product_status": "WAITING_USER_INPUT",
        "source": "ThreadStatus.activeFlags",
        "event": {"status": {"type": "active", "activeFlags": ["waitingOnUserInput"]}},
    },
    {
        "candidate_product_status": "ERROR",
        "source": "ThreadStatus",
        "event": {"status": {"type": "systemError"}},
    },
)


@dataclass(frozen=True)
class SchemaEvidence:
    """Status-related values generated by `codex app-server generate-ts`."""

    thread_status_types: tuple[str, ...]
    thread_active_flags: tuple[str, ...]
    turn_statuses: tuple[str, ...]


@dataclass(frozen=True)
class ProductStateCandidate:
    """Evidence-backed product-facing traffic-light state candidate."""

    name: str
    evidence: str
    confidence: str
    note: str


def extract_thread_status_types(source: str) -> list[str]:
    """Extract ThreadStatus `type` variants from generated TypeScript text."""
    return _dedupe(match.group("value") for match in THREAD_STATUS_RE.finditer(source))


def extract_string_union_values(source: str, type_name: str) -> list[str]:
    """Extract string values from a generated TypeScript string-literal union."""
    pattern = re.compile(STRING_UNION_RE_TEMPLATE.format(name=re.escape(type_name)), re.DOTALL)
    match = pattern.search(source)
    if match is None:
        return []
    return _dedupe(item.group("value") for item in STRING_LITERAL_RE.finditer(match.group("body")))


def collect_schema_evidence(schema_dir: Path) -> SchemaEvidence:
    """Collect traffic-light-relevant status axes from generated TypeScript files."""
    v2_dir = schema_dir / "v2"
    thread_status = _read_text(v2_dir / "ThreadStatus.ts")
    thread_active_flag = _read_text(v2_dir / "ThreadActiveFlag.ts")
    turn_status = _read_text(v2_dir / "TurnStatus.ts")
    return SchemaEvidence(
        thread_status_types=tuple(extract_thread_status_types(thread_status)),
        thread_active_flags=tuple(
            extract_string_union_values(thread_active_flag, "ThreadActiveFlag")
        ),
        turn_statuses=tuple(extract_string_union_values(turn_status, "TurnStatus")),
    )


def build_product_state_candidates() -> list[ProductStateCandidate]:
    """Return the evidence-backed product status candidates before model migration."""
    return [
        ProductStateCandidate(
            "OFFLINE",
            "No app-server connection or no Codex process",
            "high",
            "Product fallback state, not a Codex app-server enum.",
        ),
        ProductStateCandidate(
            "NOT_LOADED",
            'ThreadStatus.type == "notLoaded"',
            "high",
            "Raw Codex thread state; current product model does not represent it.",
        ),
        ProductStateCandidate(
            "IDLE",
            'ThreadStatus.type == "idle"',
            "high",
            "Raw Codex thread state.",
        ),
        ProductStateCandidate(
            "WORKING",
            'ThreadStatus.type == "active" with no activeFlags, or TurnStatus == "inProgress"',
            "high",
            "Execution state; flags refine it into waiting states.",
        ),
        ProductStateCandidate(
            "WAITING_APPROVAL",
            'ThreadStatus.activeFlags contains "waitingOnApproval"',
            "high",
            "Active thread substate.",
        ),
        ProductStateCandidate(
            "WAITING_USER_INPUT",
            'ThreadStatus.activeFlags contains "waitingOnUserInput"',
            "high",
            "Active thread substate.",
        ),
        ProductStateCandidate(
            "ERROR",
            'ThreadStatus.type == "systemError" or TurnStatus == "failed"',
            "high",
            "Raw thread/turn error state plus product fallback for abnormal exit.",
        ),
    ]


def build_non_idle_simulations() -> list[dict[str, object]]:
    """Build diagnostic sample events for all non-idle candidate product states."""
    simulations: list[dict[str, object]] = []
    for item in NON_IDLE_SIMULATION_EVENTS:
        simulation = dict(item)
        if "mapped_by_current_code" not in simulation:
            event = simulation["event"]
            if isinstance(event, Mapping):
                mapped = CodexStateMapper.map_event(event)
                simulation["mapped_by_current_code"] = None if mapped is None else mapped.name
        simulations.append(simulation)
    return simulations


def run_probe() -> dict[str, object]:
    """Run the local read-only Codex state probe and return JSON-safe evidence."""
    entrypoints = discover_codex_entrypoints()
    schema_by_entrypoint = _schema_evidence_by_entrypoint(entrypoints)
    primary_schema = _first_schema_evidence(schema_by_entrypoint)
    return {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "codex_entrypoints": entrypoints,
        "app_server_help_summary": _app_server_help_summary(),
        "schema_evidence_by_entrypoint": schema_by_entrypoint,
        "schema_evidence": asdict(primary_schema),
        "candidate_product_states": [
            asdict(candidate) for candidate in build_product_state_candidates()
        ],
        "current_project_product_statuses": _current_project_product_statuses(),
        "non_idle_simulations": build_non_idle_simulations(),
        "running_codex_processes": _running_codex_processes(),
        "hook_session_files": _hook_session_files(),
        "vscode_log_hints": _vscode_log_hints(),
        "conclusion": _build_conclusion(primary_schema, schema_by_entrypoint),
    }


def main() -> int:
    """Print probe evidence as JSON."""
    print(json.dumps(run_probe(), ensure_ascii=False, indent=2))
    return 0


def discover_codex_entrypoints() -> list[dict[str, object]]:
    """Discover global and VSCode-bundled Codex executables visible on this machine."""
    paths = dedupe_paths(_where_codex_paths() + _running_codex_executable_paths())
    entrypoints: list[dict[str, object]] = []
    for path in paths:
        version = _run_text([path, "--version"])
        entrypoints.append(
            {
                "path": path,
                "version": version,
                "kind": "vscode-extension" if ".vscode" in path.lower() else "path",
            }
        )
    return entrypoints


def dedupe_paths(paths: Iterable[str]) -> list[str]:
    """Return paths once, preserving order and using Windows case-insensitive keys."""
    result: list[str] = []
    seen: set[str] = set()
    for path in paths:
        key = path.lower()
        if key in seen:
            continue
        seen.add(key)
        result.append(path)
    return result


def _schema_evidence_by_entrypoint(
    entrypoints: list[dict[str, object]],
) -> list[dict[str, object]]:
    results: list[dict[str, object]] = []
    for index, entrypoint in enumerate(entrypoints):
        path = entrypoint.get("path")
        if not isinstance(path, str):
            continue
        output_dir = Path(tempfile.gettempdir()) / f"codex-traffic-lights-state-probe-ts-{index}"
        generation = _generate_schema(path, output_dir)
        evidence = (
            collect_schema_evidence(output_dir)
            if generation["ok"] and output_dir.exists()
            else SchemaEvidence((), (), ())
        )
        results.append(
            {
                "entrypoint": entrypoint,
                "schema_generation": generation,
                "schema_evidence": asdict(evidence),
            }
        )
    return results


def _first_schema_evidence(results: list[dict[str, object]]) -> SchemaEvidence:
    for result in results:
        evidence = result.get("schema_evidence")
        if not isinstance(evidence, dict):
            continue
        thread_status_types = evidence.get("thread_status_types")
        if isinstance(thread_status_types, list | tuple) and thread_status_types:
            return SchemaEvidence(
                thread_status_types=tuple(str(item) for item in thread_status_types),
                thread_active_flags=tuple(
                    str(item) for item in evidence.get("thread_active_flags", [])
                ),
                turn_statuses=tuple(str(item) for item in evidence.get("turn_statuses", [])),
            )
    return SchemaEvidence((), (), ())


def _generate_schema(codex_path: str, output_dir: Path) -> dict[str, object]:
    if output_dir.exists():
        shutil.rmtree(output_dir)
    command = [codex_path, "app-server", "generate-ts", "--experimental", "--out", str(output_dir)]
    completed = _run_completed(command, timeout=30)
    return {
        "ok": completed.returncode == 0,
        "command": command,
        "returncode": completed.returncode,
        "stderr": completed.stderr.strip(),
    }


def _app_server_help_summary() -> dict[str, object]:
    text = _run_text(["codex", "app-server", "--help"])
    return {
        "mentions_stdio_default": "stdio://` (default)" in text or "[default: stdio://]" in text,
        "mentions_websocket": "ws://IP:PORT" in text,
        "raw_transport_lines": [
            line.strip()
            for line in text.splitlines()
            if "--listen" in line or "stdio://" in line or "ws://IP:PORT" in line
        ],
    }


def _current_project_product_statuses() -> list[str]:
    from codex_traffic_lights.models import CodexStatus

    return [status.name for status in CodexStatus]


def _running_codex_processes() -> list[dict[str, object]]:
    command = [
        "powershell",
        "-NoProfile",
        "-Command",
        (
            "Get-CimInstance Win32_Process | "
            "Where-Object { $_.Name -match 'codex|Code' -or "
            "$_.CommandLine -match 'codex app-server' } | "
            "Select-Object ProcessId,Name,ExecutablePath,CommandLine | ConvertTo-Json -Depth 3"
        ),
    ]
    text = _run_text(command)
    parsed = _json_loads_or_none(text)
    if parsed is None:
        return []
    values = parsed if isinstance(parsed, list) else [parsed]
    return [item for item in values if isinstance(item, dict)]


def _running_codex_executable_paths() -> list[str]:
    return [
        str(item["ExecutablePath"])
        for item in _running_codex_processes()
        if item.get("Name") == "codex.exe" and isinstance(item.get("ExecutablePath"), str)
    ]


def _hook_session_files() -> list[dict[str, object]]:
    sessions_dir = Path.home() / ".codex-traffic-lights" / "sessions"
    if not sessions_dir.exists():
        return []

    files: list[dict[str, object]] = []
    for path in sorted(sessions_dir.glob("*.json")):
        payload = _json_loads_or_none(_read_text(path))
        files.append(
            {
                "name": path.name,
                "modified_at": path.stat().st_mtime,
                "payload": payload if isinstance(payload, dict) else None,
            }
        )
    return files


def _vscode_log_hints() -> list[dict[str, object]]:
    root = Path.home() / "AppData" / "Roaming" / "Code" / "logs"
    if not root.exists():
        return []

    patterns = ("thread-stream-state-changed", "thread-read-state-changed", "client-status-changed")
    candidates = sorted(
        root.rglob("*.log"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )[:80]
    hints: list[dict[str, object]] = []
    for path in candidates:
        with path.open("r", encoding="utf-8", errors="ignore") as handle:
            lines = handle.readlines()[-300:]
        matched = [line.strip() for line in lines if any(pattern in line for pattern in patterns)]
        if matched:
            hints.append({"path": str(path), "matches": matched[-10:]})
    return hints[:10]


def _where_codex_paths() -> list[str]:
    completed = _run_completed(["where.exe", "codex"], timeout=10)
    if completed.returncode != 0:
        return []
    return [line.strip() for line in completed.stdout.splitlines() if line.strip()]


def _build_conclusion(
    evidence: SchemaEvidence,
    schema_by_entrypoint: list[dict[str, object]],
) -> dict[str, object]:
    candidate_count = len(build_product_state_candidates())
    schemas_match = _schema_signatures(schema_by_entrypoint)
    return {
        "raw_thread_status_type_count": len(evidence.thread_status_types),
        "raw_thread_status_types": list(evidence.thread_status_types),
        "raw_active_flag_count": len(evidence.thread_active_flags),
        "raw_active_flags": list(evidence.thread_active_flags),
        "raw_turn_status_count": len(evidence.turn_statuses),
        "raw_turn_statuses": list(evidence.turn_statuses),
        "candidate_product_state_count": candidate_count,
        "candidate_product_state_names": [
            candidate.name for candidate in build_product_state_candidates()
        ],
        "important_distinction": (
            "ThreadStatus, activeFlags, and TurnStatus are separate protocol axes; "
            "do not add them together as one native state count."
        ),
        "current_gap": (
            "The current project model omits NOT_LOADED and maps ThreadStatus.notLoaded to None."
        ),
        "entrypoint_schema_signatures": sorted(schemas_match),
        "entrypoint_schemas_match": len(schemas_match) <= 1,
    }


def _schema_signatures(schema_by_entrypoint: list[dict[str, object]]) -> set[str]:
    signatures: set[str] = set()
    for result in schema_by_entrypoint:
        generation = result.get("schema_generation")
        if not isinstance(generation, dict) or generation.get("ok") is not True:
            continue
        evidence = result.get("schema_evidence")
        if not isinstance(evidence, dict):
            continue
        signatures.add(json.dumps(evidence, sort_keys=True))
    return signatures


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore") if path.exists() else ""


def _run_text(command: list[str]) -> str:
    completed = _run_completed(command, timeout=15)
    return (completed.stdout or completed.stderr).strip()


def _run_completed(command: list[str], *, timeout: int) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return subprocess.CompletedProcess(command, 1, "", str(exc))


def _json_loads_or_none(text: str) -> Any | None:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return None


def _dedupe(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value not in seen:
            seen.add(value)
            result.append(value)
    return result


if __name__ == "__main__":
    raise SystemExit(main())
